Snapshot of kokkos.git from commit c1c9e8d6b30e58b04700bb4602494bb417d42fbc
From repository at git@github.com:/kokkos/kokkos.git

At commit:
commit c1c9e8d6b30e58b04700bb4602494bb417d42fbc
Author: crtrott <crtrott@sandia.gov>
Date:   Tue Dec 8 23:06:55 2015 -0700

    Core: fix another issue with the memory tracking, introduced recently

    There was a bug introduced when solving the performance issues with
    subviews. It seemed to not have trickered any errors in either Trilinos
    tests nor kokkos tests, but did crash Nalu.

diff --git a/lib/kokkos/config/test_all_sandia b/lib/kokkos/config/test_all_sandia
--- a/lib/kokkos/config/test_all_sandia
+++ b/lib/kokkos/config/test_all_sandia
@@ -6,8 +6,6 @@
 
 set -o pipefail
 
-COMPILER_ROOT="/home/projects/x86-64"
-
 GCC_BUILD_LIST="OpenMP,Pthread,Serial,OpenMP_Serial,Pthread_Serial"
 INTEL_BUILD_LIST="OpenMP,Pthread,Serial,OpenMP_Serial,Pthread_Serial"
 CLANG_BUILD_LIST="Pthread,Serial,Pthread_Serial"
@@ -18,24 +16,17 @@ CLANG_WARNING_FLAGS="-Wall,-Wshadow,-pedantic,-Werror,-Wsign-compare,-Wtype-limi
 INTEL_WARNING_FLAGS="-Wall,-Wshadow,-pedantic,-Werror,-Wsign-compare,-Wtype-limits,-Wuninitialized"
 CUDA_WARNING_FLAGS=""
 
-# Format: (compiler module-list build-list exe-name warning-flag)
-COMPILERS=("gcc/4.7.2 gcc/4.7.2/base,hwloc/1.10.0/host/gnu/4.7.2 $GCC_BUILD_LIST g++ $GCC_WARNING_FLAGS"
-           "gcc/4.8.4 gcc/4.9.2/base,hwloc/1.10.0/host/gnu/4.9.2 $GCC_BUILD_LIST g++ $GCC_WARNING_FLAGS"
-           "gcc/4.9.2 gcc/4.9.2/base,hwloc/1.10.0/host/gnu/4.9.2 $GCC_BUILD_LIST g++ $GCC_WARNING_FLAGS"
-           "gcc/5.1.0 gcc/5.1.0/base,hwloc/1.10.0/host/gnu/5.1.0 $GCC_BUILD_LIST g++ $GCC_WARNING_FLAGS"
-           "intel/14.0.4 intel/14.0.4/base,hwloc/1.10.0/host/gnu/4.7.2 $INTEL_BUILD_LIST icpc $INTEL_WARNING_FLAGS"
-           "intel/15.0.2 intel/15.0.2/base,hwloc/1.10.0/host/gnu/4.7.2 $INTEL_BUILD_LIST icpc $INTEL_WARNING_FLAGS"
-           "clang/3.5.2 clang/3.5.2/base $CLANG_BUILD_LIST clang++ $CLANG_WARNING_FLAGS"
-           "clang/3.6.1 clang/3.6.1/base $CLANG_BUILD_LIST clang++ $CLANG_WARNING_FLAGS"
-           "cuda/6.5.14 cuda/6.5.14,nvcc-wrapper/gnu,gcc/4.7.2/base $CUDA_BUILD_LIST nvcc_wrapper $CUDA_WARNING_FLAGS"
-           "cuda/7.0.28 cuda/7.0.18,nvcc-wrapper/gnu,gcc/4.7.2/base $CUDA_BUILD_LIST nvcc_wrapper $CUDA_WARNING_FLAGS"
-           )
+BASE_MODULE_LIST="<COMPILER_NAME>/<COMPILER_VERSION>/base,hwloc/1.10.1/<COMPILER_NAME>/<COMPILER_VERSION>/base"
+CUDA_MODULE_LIST="<COMPILER_NAME>/<COMPILER_VERSION>,gcc/4.7.2/base"
 
 export OMP_NUM_THREADS=4
 
-export SEMS_MODULE_ROOT=/projects/modulefiles
-module use /home/projects/modulefiles
-module use /projects/modulefiles/rhel6-x86_64/sems/compiler
+declare -i NUM_RESULTS_TO_KEEP=7
+
+RESULT_ROOT_PREFIX=TestAll
+
+source /projects/modulefiles/utils/sems-modules-init.sh
+source /projects/modulefiles/utils/kokkos-modules-init.sh
 
 SCRIPT_KOKKOS_ROOT=$( cd "$( dirname "$0" )" && cd .. && pwd )
 
@@ -47,6 +38,9 @@ DEBUG=False
 ARGS=""
 CUSTOM_BUILD_LIST=""
 DRYRUN=False
+BUILD_ONLY=False
+declare -i NUM_JOBS_TO_RUN_IN_PARALLEL=3
+TEST_SCRIPT=False
 
 while [[ $# > 0 ]]
 do
@@ -61,6 +55,15 @@ CUSTOM_BUILD_LIST="${key#*=}"
 --debug*)
 DEBUG=True
 ;;
+--build-only*)
+BUILD_ONLY=True
+;;
+--test-script*)
+TEST_SCRIPT=True
+;;
+--num*)
+NUM_JOBS_TO_RUN_IN_PARALLEL="${key#*=}"
+;;
 --dry-run*)
 DRYRUN=True
 ;;
@@ -69,7 +72,10 @@ echo "test_all_sandia <ARGS> <OPTIONS>:"
 echo "--kokkos-path=/Path/To/Kokkos: Path to the Kokkos root directory"
 echo "    Defaults to root repo containing this script"
 echo "--debug: Run tests in debug. Defaults to False"
+echo "--test-script: Test this script, not Kokkos"
+echo "--num=N: Number of jobs to run in parallel "
 echo "--dry-run: Just print what would be executed"
+echo "--build-only: Just do builds, don't run anything"
 echo "--build-list=BUILD,BUILD,BUILD..."
 echo "    Provide a comma-separated list of builds instead of running all builds"
 echo "    Valid items:"
@@ -77,6 +83,18 @@ echo "      OpenMP, Pthread, Serial, OpenMP_Serial, Pthread_Serial"
 echo "      Cuda_OpenMP, Cuda_Pthread, Cuda_Serial"
 echo ""
 echo "ARGS: list of expressions matching compilers to test"
+echo "  supported compilers"
+echo "    gcc/4.7.2"
+echo "    gcc/4.8.4"
+echo "    gcc/4.9.2"
+echo "    gcc/5.1.0"
+echo "    intel/14.0.4"
+echo "    intel/15.0.2"
+echo "    clang/3.5.2"
+echo "    clang/3.6.1"
+echo "    cuda/6.5.14"
+echo "    cuda/7.0.28"
+echo "    cuda/7.5.18"
 echo ""
 echo "Examples:"
 echo "  Run all tests"
@@ -93,6 +111,10 @@ echo "  % test_all_sandia --debug"
 echo ""
 echo "  Run gcc/4.7.2 and only do OpenMP and OpenMP_Serial builds"
 echo "  % test_all_sandia gcc/4.7.2 --build-list=OpenMP,OpenMP_Serial"
+echo ""
+echo "If you want to kill the tests, do:"
+echo "  hit ctrl-z"
+echo "  % kill -9 %1"
 echo
 exit 0
 ;;
@@ -103,7 +125,6 @@ ARGS="$ARGS $1"
 esac
 shift
 done
-
 
 # set kokkos path
 if [ -z "$KOKKOS_PATH" ]; then
@@ -125,12 +146,26 @@ if [ -z "$ARGS" ]; then
     ARGS='?'
 fi
 
+# Format: (compiler module-list build-list exe-name warning-flag)
+COMPILERS=("gcc/4.7.2 $BASE_MODULE_LIST $GCC_BUILD_LIST g++ $GCC_WARNING_FLAGS"
+           "gcc/4.8.4 $BASE_MODULE_LIST $GCC_BUILD_LIST g++ $GCC_WARNING_FLAGS"
+           "gcc/4.9.2 $BASE_MODULE_LIST $GCC_BUILD_LIST g++ $GCC_WARNING_FLAGS"
+           "gcc/5.1.0 $BASE_MODULE_LIST $GCC_BUILD_LIST g++ $GCC_WARNING_FLAGS"
+           "intel/14.0.4 $BASE_MODULE_LIST $INTEL_BUILD_LIST icpc $INTEL_WARNING_FLAGS"
+           "intel/15.0.2 $BASE_MODULE_LIST $INTEL_BUILD_LIST icpc $INTEL_WARNING_FLAGS"
+           "clang/3.5.2 $BASE_MODULE_LIST $CLANG_BUILD_LIST clang++ $CLANG_WARNING_FLAGS"
+           "clang/3.6.1 $BASE_MODULE_LIST $CLANG_BUILD_LIST clang++ $CLANG_WARNING_FLAGS"
+           "cuda/6.5.14 $CUDA_MODULE_LIST $CUDA_BUILD_LIST $KOKKOS_PATH/config/nvcc_wrapper $CUDA_WARNING_FLAGS"
+           "cuda/7.0.28 $CUDA_MODULE_LIST $CUDA_BUILD_LIST $KOKKOS_PATH/config/nvcc_wrapper $CUDA_WARNING_FLAGS"
+           "cuda/7.5.18 $CUDA_MODULE_LIST $CUDA_BUILD_LIST $KOKKOS_PATH/config/nvcc_wrapper $CUDA_WARNING_FLAGS"
+           )
+
 # Process args to figure out which compilers to test
 COMPILERS_TO_TEST=""
 for ARG in $ARGS; do
     for COMPILER_DATA in "${COMPILERS[@]}"; do
-        arr=($COMPILER_DATA)
-        COMPILER=${arr[0]}
+        ARR=($COMPILER_DATA)
+        COMPILER=${ARR[0]}
         if [[ "$COMPILER" = $ARG* ]]; then
             if [[ "$COMPILERS_TO_TEST" != *${COMPILER}* ]]; then
                 COMPILERS_TO_TEST="$COMPILERS_TO_TEST $COMPILER"
@@ -145,15 +180,28 @@ done
 # Functions
 #
 
+# get_compiler_name <COMPILER>
+get_compiler_name() {
+    echo $1 | cut -d/ -f1
+}
+
+# get_compiler_version <COMPILER>
+get_compiler_version() {
+    echo $1 | cut -d/ -f2
+}
+
 # Do not call directly
 get_compiler_data() {
-    compiler=$1
-    item=$2
+    local compiler=$1
+    local item=$2
+    local compiler_name=$(get_compiler_name $compiler)
+    local compiler_vers=$(get_compiler_version $compiler)
 
+    local compiler_data
     for compiler_data in "${COMPILERS[@]}" ; do
-        arr=($compiler_data)
+        local arr=($compiler_data)
         if [ "$compiler" = "${arr[0]}" ]; then
-            echo "${arr[$item]}" | tr , ' '
+            echo "${arr[$item]}" | tr , ' ' | sed -e "s/<COMPILER_NAME>/$compiler_name/g" -e "s/<COMPILER_VERSION>/$compiler_vers/g"
             return 0
         fi
     done
@@ -186,19 +234,41 @@ get_compiler_warning_flags() {
 run_cmd() {
     echo "RUNNING: $*"
     if [ "$DRYRUN" != "True" ]; then
-	eval "$*"
+	eval "$* 2>&1"
     fi
 }
 
+# report_and_log_test_results <SUCCESS> <DESC> <PHASE>
 report_and_log_test_result() {
-    if [ "$1" = "0" ]; then
-	echo "PASSED $2"
-	TEST_RESULTS="${TEST_RESULTS}\nPASSED $2"
+    # Use sane var names
+    local success=$1; local desc=$2; local phase=$3;
+
+    if [ "$success" = "0" ]; then
+	echo "  PASSED $desc"
+        touch $PASSED_DIR/$desc
     else
-	echo "FAILED $2" >&2
-	TEST_RESULTS="${TEST_RESULTS}\nFAILED $2 ($3)"
-	NUM_FAILED+=1
+	echo "  FAILED $desc" >&2
+        echo $phase > $FAILED_DIR/$desc
+        cat ${desc}.${phase}.log
     fi
+}
+
+setup_env() {
+    local compiler=$1
+    local compiler_modules=$(get_compiler_modules $compiler)
+
+    module purge
+
+    local mod
+    for mod in $compiler_modules; do
+	module load $mod 2>&1
+        # It is ridiculously hard to check for the success of a loaded
+        # module. Module does not return error codes and piping to grep
+        # causes module to run in a subshell.
+        module list 2>&1 | grep "$mod" >& /dev/null || return 1
+    done
+
+    return 0
 }
 
 # single_build_and_test <COMPILER> <BUILD> <BUILD_TYPE>
@@ -206,13 +276,18 @@ single_build_and_test() {
     # Use sane var names
     local compiler=$1; local build=$2; local build_type=$3;
 
-    cd $ROOT_DIR/$compiler
+    # set up env
+    mkdir -p $ROOT_DIR/$compiler/"${build}-$build_type"
+    cd $ROOT_DIR/$compiler/"${build}-$build_type"
+    local desc=$(echo "${compiler}-${build}-${build_type}" | sed 's:/:-:g')
+    setup_env $compiler >& ${desc}.configure.log || { report_and_log_test_result 1 ${desc} configure && return 0; }
 
+    # Set up flags
     local compiler_warning_flags=$(get_compiler_warning_flags $compiler)
     local compiler_exe=$(get_compiler_exe_name $compiler)
 
     if [[ "$build_type" = hwloc* ]]; then
-        local extra_args="--with-hwloc=$HWLOC_ROOT"
+        local extra_args=--with-hwloc=$(dirname $(dirname $(which hwloc-info)))
     fi
 
     if [[ "$build_type" = *debug* ]]; then
@@ -222,34 +297,61 @@ single_build_and_test() {
         local cxxflags="-O3 $compiler_warning_flags"
     fi
 
-    local desc=$(echo "${compiler}-${build}-${build_type}" | sed 's:/:-:g')
-    echo "  Doing build: $desc"
-
-    mkdir "${build}-$build_type"
-    cd "${build}-$build_type"
+    if [[ "$compiler" == cuda* ]]; then
+        cxxflags="--keep --keep-dir=$(pwd) $cxxflags"
+        export TMPDIR=$(pwd)
+    fi
 
     # cxxflags="-DKOKKOS_USING_EXPERIMENTAL_VIEW $cxxflags"
 
-    run_cmd ${KOKKOS_PATH}/generate_makefile.bash --with-devices=$build --compiler=$(which $compiler_exe) --cxxflags=\"$cxxflags\" \"$extra_args\" 2>&1 | tee ${desc}.configure.log || { report_and_log_test_result 1 ${desc} configure && return 0; }
-    run_cmd make build-test 2>&1 | tee ${desc}.build.log || { report_and_log_test_result 1 ${desc} build && return 0; }
-    run_cmd make test 2>&1 | tee ${desc}.test.log || { report_and_log_test_result 1 ${desc} test && return 0; }
+    echo "  Starting job $desc"
+
+    if [ "$TEST_SCRIPT" = "True" ]; then
+        local rand=$[ 1 + $[ RANDOM % 10 ]]
+        sleep $rand
+        if [ $rand -gt 5 ]; then
+            run_cmd ls fake_problem >& ${desc}.configure.log || { report_and_log_test_result 1 $desc configure && return 0; }
+        fi
+    else
+        run_cmd ${KOKKOS_PATH}/generate_makefile.bash --with-devices=$build --compiler=$(which $compiler_exe) --cxxflags=\"$cxxflags\" $extra_args >& ${desc}.configure.log || { report_and_log_test_result 1 ${desc} configure && return 0; }
+        run_cmd make build-test >& ${desc}.build.log || { report_and_log_test_result 1 ${desc} build && return 0; }
+        if [[ "$BUILD_ONLY" == False ]]; then
+            run_cmd make test >& ${desc}.test.log || { report_and_log_test_result 1 ${desc} test && return 0; }
+        fi
+    fi
+
     report_and_log_test_result 0 $desc
+
     return 0
 }
 
-setup_env() {
-    local compiler=$1
-    local compiler_modules=$(get_compiler_modules $compiler)
-
-    module purge
-
-    for mod in $compiler_modules; do
-	module load $mod
-        # It is ridiculously hard to check for the success of a loaded
-        # module. Module does not return error codes and piping to grep
-        # causes module to run in a subshell.
-        module list 2>&1 | grep "$mod"
+# wait_for_jobs <NUM-JOBS>
+wait_for_jobs() {
+    local -i max_jobs=$1
+    local -i num_active_jobs=$(jobs | wc -l)
+    while [ $num_active_jobs -ge $max_jobs ]
+    do
+        sleep 1
+        num_active_jobs=$(jobs | wc -l)
+        jobs >& /dev/null
     done
+}
+
+# run_in_background <COMPILER> <BUILD> <BUILD_TYPE>
+run_in_background() {
+    local compiler=$1
+
+    local -i num_jobs=$NUM_JOBS_TO_RUN_IN_PARALLEL
+    if [[ "$BUILD_ONLY" == True ]]; then
+        num_jobs=8
+    else
+        if [[ "$compiler" == cuda* ]]; then
+            num_jobs=1
+        fi
+    fi
+    wait_for_jobs $num_jobs
+
+    single_build_and_test $* &
 }
 
 # build_and_test_all <COMPILER>
@@ -262,44 +364,74 @@ build_and_test_all() {
 	local compiler_build_list=$(echo "$CUSTOM_BUILD_LIST" | tr , ' ')
     fi
 
-    # set up env
-    cd $ROOT_DIR
-    mkdir -p $compiler
-    setup_env $compiler
-
     # do builds
+    local build
     for build in $compiler_build_list
     do
-	single_build_and_test $compiler $build $BUILD_TYPE
+	run_in_background $compiler $build $BUILD_TYPE
 
         # If not cuda, do a hwloc test too
         if [[ "$compiler" != cuda* ]]; then
-            single_build_and_test $compiler $build "hwloc-$BUILD_TYPE"
+            run_in_background $compiler $build "hwloc-$BUILD_TYPE"
         fi
     done
 
     return 0
 }
 
+get_test_root_dir() {
+    local existing_results=$(find . -maxdepth 1 -name "$RESULT_ROOT_PREFIX*" | sort)
+    local -i num_existing_results=$(echo $existing_results | tr ' ' '\n' | wc -l)
+    local -i num_to_delete=${num_existing_results}-${NUM_RESULTS_TO_KEEP}
+
+    if [ $num_to_delete -gt 0 ]; then
+        /bin/rm -rf $(echo $existing_results | tr ' ' '\n' | head -n $num_to_delete)
+    fi
+
+    echo $(pwd)/${RESULT_ROOT_PREFIX}_$(date +"%Y-%m-%d_%H.%M.%S")
+}
+
+wait_summarize_and_exit() {
+    wait_for_jobs 1
+
+    echo "#######################################################"
+    echo "PASSED TESTS"
+    echo "#######################################################"
+
+    \ls -1 $PASSED_DIR | sort
+
+    echo "#######################################################"
+    echo "FAILED TESTS"
+    echo "#######################################################"
+
+    local failed_test
+    local -i rv=0
+    for failed_test in $(\ls -1 $FAILED_DIR)
+    do
+        echo $failed_test "("$(cat $FAILED_DIR/$failed_test)" failed)"
+        rv=$rv+1
+    done
+
+    exit $rv
+}
+
 #
 # Main
 #
 
-/bin/rm -rf TestAll
-mkdir TestAll
-cd TestAll
+ROOT_DIR=$(get_test_root_dir)
+mkdir -p $ROOT_DIR
+cd $ROOT_DIR
 
-TEST_RESULTS=""
-declare -i NUM_FAILED=0
-ROOT_DIR=$(pwd)
+PASSED_DIR=$ROOT_DIR/results/passed
+FAILED_DIR=$ROOT_DIR/results/failed
+mkdir -p $PASSED_DIR
+mkdir -p $FAILED_DIR
+
+echo "Going to test compilers: " $COMPILERS_TO_TEST
 for COMPILER in $COMPILERS_TO_TEST; do
     echo "Testing compiler $COMPILER"
     build_and_test_all $COMPILER
 done
 
-echo "#######################################################"
-echo "RESULT SUMMARY"
-echo "#######################################################"
-echo -e $TEST_RESULTS
-
-exit $NUM_FAILED
+wait_summarize_and_exit
